import NextHead from "next/head";

function Meta({ name, content }) {
  return <meta name={name} content={content} />;
}

Head.Meta = Meta;

export default function Head({ title, children }) {
  return (
    <NextHead>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      {children}
    </NextHead>
  );
}
