const synergiesData = [
  {
    uuid: "e250ce31-45e0-499b-86b6-b137be307610",
    name: "Shout of Hatred",
    type: "Flat Percent Damage (Burst)",
    className: "Gunlancer",
    image: "https://lostarkcodex.com/icons/gl_skill_01_14.webp",
    synergy: ["3% Damage", "9% Head/Back Attack Damage"],
    duration: "12 seconds",
    uptime: "Low",
  },
  {
    uuid: "cc5090fa-2736-4200-bc0c-34bce25c45e6",
    name: "Red Dust",
    type: "Flat Percent Damage (Burst)",
    className: "Berserker",
    image: "https://lostarkcodex.com/icons/bk_skill_01_8.webp",
    synergy: ["6% Damage"],
    duration: "6 seconds",
    uptime: "Low",
  },
  {
    uuid: "cc59f650-8162-4662-83a6-10e73f922978",
    name: "Fierce Tiger Strike",
    type: "Flat Percent Damage (Burst)",
    className: "Scrapper",
    image: "https://lostarkcodex.com/icons/if_skill_01_14.webp",
    synergy: ["6% Damage"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "a0a7fe4b-a92d-45a9-938e-a57abfe0c776",
    name: "Crushing Smite",
    type: "Flat Percent Damage (Burst)",
    className: "Scrapper",
    image: "https://lostarkcodex.com/icons/if_skill_01_2.webp",
    synergy: ["6% Damage"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "e2a27cee-1184-4b9d-9edb-1aff7773fcc0",
    name: "Judgment",
    type: "Flat Percent Damage (Burst)",
    className: "Scrapper",
    image: "https://lostarkcodex.com/icons/if_skill_01_9.webp",
    synergy: ["6% Damage"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "e38fa651-281b-4167-ac3e-151d7c8596e3",
    type: "Flat Percent Damage (Constant)",
    className: "Sorceress",
    name: "Blaze",
    image: "https://lostarkcodex.com/icons/scs_skill_01_3.webp",
    synergy: ["6% Damage"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "f7deb9a9-39ac-4e89-9c90-bb8bcecf017e",
    type: "Flat Percent Damage (Constant)",
    className: "Sorceress",
    name: "Lightning Vortex",
    image: "https://lostarkcodex.com/icons/scs_skill_01_12.webp",
    synergy: ["6% Damage"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "705e50cf-c364-43a8-8069-11e09a621585",
    type: "Flat Percent Damage (Constant)",
    className: "Sharpshooter",
    name: "Rapid Shot",
    image: "https://lostarkcodex.com/icons/he_skill_01_1.webp",
    synergy: ["6% Damage"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "2f97ce3f-aac0-4612-ba8a-20f27ed9979e",
    type: "Flat Percent Damage (Constant)",
    className: "Sharpshooter",
    name: "Atomic Arrow",
    image: "https://lostarkcodex.com/icons/he_skill_01_3.webp",
    synergy: ["6% Damage"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "64b8acc3-39a4-468b-abd8-c6d188863627",
    type: "Flat Percent Damage (Constant)",
    className: "Deathblade",
    name: "Spincutter",
    image: "https://lostarkcodex.com/icons/bl_skill_01_8.webp",
    synergy: ["3% Damage", "9% Head/Back Attack Damage"],
    duration: "10 seconds",
    uptime: "High",
  },
  {
    uuid: "e54f404c-de9a-4a5d-9f96-2882d1eb5bbd",
    type: "Flat Percent Damage (Constant)",
    className: "Shadowhunter",
    name: "Howl",
    image: "https://lostarkcodex.com/icons/dm_skill_01_18.webp",
    synergy: ["6% Damage"],
    duration: "16 seconds",
    uptime: "High",
  },
  {
    type: "Flat Percent Damage (Constant)",
    uuid: "ac5a590d-34ef-48e0-b32b-935ac89faf4d",
    className: "Shadowhunter",
    name: "Demonic Slash",
    image: "https://lostarkcodex.com/icons/dm_skill_01_4.webp",
    synergy: ["6% Damage"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "c074d68a-0e16-4483-ae51-093769d0c23a",
    type: "Flat Percent Damage (Constant)",
    className: "Shadowhunter",
    name: "Ruining Rush",
    image: "https://lostarkcodex.com/icons/dm_skill_01_20.webp",
    synergy: ["6% Damage"],
    duration: "6 seconds",
    uptime: "High",
  },
  {
    uuid: "1a50a292-0c0b-4980-afc1-ee6189da25d6",
    type: "Flat Percent Damage (Constant)",
    className: "Shadowhunter",
    name: "Death Claw",
    image: "https://lostarkcodex.com/icons/dm_skill_01_21.webp",
    synergy: ["6% Damage"],
    duration: "6 seconds",
    uptime: "High",
  },
  {
    uuid: "2049fee9-614f-4ae0-b4a0-3326460876ae",
    type: "Attack Power",
    className: "Machinist",
    name: "Overcharged Battery",
    image: "https://lostarkcodex.com/icons/sc_skill_01_4.webp",
    synergy: ["6% Attack Power"],
    duration: "14 seconds",
    uptime: "High",
  },
  {
    uuid: "533e76d5-c48f-4048-82f1-e7872bce4caf",
    type: "Attack Power",
    className: "Soulfist",
    name: "Energy Release",
    image: "https://lostarkcodex.com/icons/so_skill_01_20.webp",
    synergy: ["6% Attack Power"],
    duration: "16 seconds",
    uptime: "Medium",
  },
  {
    uuid: "c07001fb-fa26-48aa-bc2a-8589aec2be77",
    type: "Attack Power",
    className: "Soulfist",
    name: "Pulverizing Palm",
    image: "https://lostarkcodex.com/icons/so_skill_01_13.webp",
    synergy: ["6% Attack Power"],
    duration: "8 seconds",
    uptime: "Medium",
  },
  {
    uuid: "797473d1-b41f-4a0b-9ef9-f8f3a9f7900e",
    type: "Attack Power",
    className: "Soulfist",
    name: "Bolting Crash",
    image: "https://lostarkcodex.com/icons/so_skill_01_17.webp",
    synergy: ["6% Attack Power"],
    duration: "10 seconds",
    uptime: "High",
  },
  {
    uuid: "3058eed4-25cb-494f-a7f4-0ccf32d46888",
    type: "Crit Rate (Burst)",
    className: "Wardancer",
    name: "Roar of Courage",
    image: "https://lostarkcodex.com/icons/bm_skill_01_4.webp",
    synergy: ["18% Crit Rate"],
    duration: "8 seconds",
    uptime: "Low",
  },
  {
    uuid: "b2b86994-f8f0-4a20-a15c-7975c3e79554",
    type: "Crit Rate (Burst)",
    className: "Striker",
    name: "Lightning Whisper",
    image: "https://lostarkcodex.com/icons/bm_skill_01_28.webp",
    synergy: ["18% Crit Rate"],
    duration: "6 seconds",
    uptime: "Low",
  },
  {
    uuid: "8536a987-b006-425b-bf07-f9a6d52507d6",
    type: "Crit Rate (Burst)",
    className: "Glaivier",
    name: "Shackling Blue Dragon",
    image: "https://lostarkcodex.com/icons/lm_skill_01_18.webp",
    synergy: ["18% Crit Rate"],
    duration: "6 seconds",
    uptime: "Low",
  },
  {
    uuid: "c3e7e4d4-e33f-42b3-89c0-0d3e9df4fda2",
    type: "Crit Rate (Burst)",
    className: "Gunlancer",
    name: "Lance of Judgment",
    image: "https://lostarkcodex.com/icons/gl_skill_01_34.webp",
    synergy: ["10% Crit Rate"],
    duration: "10 seconds",
    uptime: "Very Low",
  },
  {
    uuid: "9dc2e728-739c-4b15-8c50-a57027aeb6f1",
    type: "Crit Rate (Constant)",
    className: "Deadeye",
    name: "Spiral Tracker",
    image: "https://lostarkcodex.com/icons/dh_skill_01_9.webp",
    synergy: ["10% Crit Rate"],
    duration: "6 seconds",
    uptime: "High",
  },
  {
    uuid: "bbb2001b-4dec-40bf-b209-685740af9ced",
    type: "Crit Rate (Constant)",
    className: "Deadeye",
    name: "AT02 Grenade",
    image: "https://lostarkcodex.com/icons/dh_skill_01_8.webp",
    synergy: ["10% Crit Rate"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "388f49d4-98a7-4e63-910c-ff12008389d3",
    type: "Crit Rate (Constant)",
    className: "Gunslinger",
    name: "Spiral Tracker",
    image: "https://lostarkcodex.com/icons/dh_skill_01_9.webp",
    synergy: ["10% Crit Rate"],
    duration: "6 seconds",
    uptime: "High",
  },
  {
    uuid: "9634628d-63c3-4993-b712-5981db5b960b",
    type: "Crit Rate (Constant)",
    className: "Gunslinger",
    name: "Dexterous Shot",
    image: "https://lostarkcodex.com/icons/dh_skill_01_36.webp",
    synergy: ["10% Crit Rate"],
    duration: "6 seconds",
    uptime: "High",
  },
  {
    uuid: "133e432d-5424-4527-b242-d3dfa1aeff89",
    type: "Crit Rate (Constant)",
    className: "Gunslinger",
    name: "Equilibrium",
    image: "https://lostarkcodex.com/icons/dh_skill_01_20.webp",
    synergy: ["10% Crit Rate"],
    duration: "12 seconds",
    uptime: "High",
  },
  {
    uuid: "e0bcdbd5-7699-4d8b-9269-f85572481795",
    type: "Crit Rate (Constant)",
    className: "Arcanist",
    name: "Return",
    image: "https://lostarkcodex.com/icons/ac_skill_01_15.webp",
    synergy: ["10% Crit Rate"],
    duration: "10 seconds",
    uptime: "High",
  },
  {
    uuid: "eef07feb-2c50-45e2-a104-719a580957ef",
    type: "Crit Rate (Constant)",
    className: "Arcanist",
    name: "Quadra Accelerate",
    image: "https://lostarkcodex.com/icons/ac_skill_01_9.webp",
    synergy: ["10% Crit Rate"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "bd74d063-a50d-43a8-90f3-4017658dd1a2",
    type: "Crit Rate (Constant)",
    className: "Arcanist",
    name: "Scratch Dealer",
    image: "https://lostarkcodex.com/icons/ac_skill_01_24.webp",
    synergy: ["10% Crit Rate"],
    duration: "10 seconds",
    uptime: "High",
  },
  {
    uuid: "bd997a45-22e4-49dd-ab18-02098b69837a",
    type: "Defense Reduction",
    className: "Artillerist",
    name: "Summon Turret",
    image: "https://lostarkcodex.com/icons/bs_skill_01_5.webp",
    synergy: ["12% Defense Reduction"],
    duration: "6 seconds",
    uptime: "High",
  },
  {
    uuid: "bca07d49-0259-4293-8a83-f06379f20ec8",
    type: "Defense Reduction",
    className: "Artillerist",
    name: "Enhanced Shell",
    image: "https://lostarkcodex.com/icons/bs_skill_01_0.webp",
    synergy: ["12% Defense Reduction"],
    duration: "8 seconds",
    uptime: "High",
  },
  {
    uuid: "fbd72c02-4e5b-44db-846d-c6b8633b7c2f",
    type: "Defense Reduction",
    className: "Gunlancer",
    name: "Bash",
    image: "https://lostarkcodex.com/icons/gl_skill_01_1.webp",
    synergy: ["12% Defense Reduction"],
    duration: "10 seconds",
    uptime: "High",
  },
  {
    uuid: "2bfcdb20-33c9-4de4-a48f-47aa43281fad",
    type: "Defense Reduction",
    className: "Destroyer",
    name: "Jumping Smash",
    image: "https://lostarkcodex.com/icons/dt_skill_01_12.webp",
    synergy: ["12% Defense Reduction"],
    duration: "14 seconds",
    uptime: "High",
  },
  {
    uuid: "8591d731-05fd-4ee5-9ec4-3d61d11f60f6",
    type: "Defense Reduction",
    className: "Destroyer",
    name: "Power Strike",
    image: "https://lostarkcodex.com/icons/dt_skill_01_14.webp",
    synergy: ["12% Defense Reduction"],
    duration: "10 seconds",
    uptime: "High",
  },
];

export default synergiesData;
